version: '3.6'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www
    links:
      - php
    depends_on:
      - php
    networks:
      - outside
  php:
    volumes:
       - ../:/var/www
    image: php:7.3-fpm
    networks:
      - outside

#  mariadb:
#      image: mariadb:10.4
#      ports:
#          - "33306:3306"
#      environment:
#          MYSQL_ROOT_PASSWORD: 123
#      volumes:
#          - mariadb:/var/lib/mysql
#      networks:
#          - outside

networks:
  outside:
    driver: bridge

volumes:
    mariadb: {}
